const WORDS = [
  // ── Animale ──────────────────────────────────────────────────────────────────
  { word: "ELEFANT",       hint: "Animal mare cu trompă",                           level: 1 },
  { word: "GIRAFĂ",        hint: "Animal cu gât lung",                              level: 1 },
  { word: "PINGUIN",       hint: "Pasăre care nu zboară, trăiește la pol",          level: 1 },
  { word: "CROCODIL",      hint: "Reptilă mare, trăiește în apă",                   level: 1 },
  { word: "PAPAGAL",       hint: "Pasăre colorată care imită vorbirea",             level: 1 },
  { word: "LEOPARD",       hint: "Felină cu pete",                                  level: 1 },
  { word: "STRUȚ",         hint: "Cea mai mare pasăre din lume",                    level: 1 },
  { word: "DELFIN",        hint: "Mamifer marin foarte inteligent",                 level: 1 },
  { word: "RECHIN",        hint: "Pește mare, prădător al oceanului",               level: 1 },
  { word: "KOALA",         hint: "Marsupial australian care mănâncă eucalipt",      level: 1 },
  { word: "PANDA",         hint: "Urs alb-negru din China",                         level: 1 },
  { word: "TIGRU",         hint: "Felină cu dungi",                                 level: 1 },
  { word: "FLAMINGO",      hint: "Pasăre roz cu picioare lungi",                    level: 2 },
  { word: "HIPOPOTAM",     hint: "Animal masiv, trăiește în râuri africane",        level: 2 },
  { word: "VULTURE",       hint: "Pasăre răpitoare care se hrănește cu hoituri",    level: 2 },

  // ── Fructe ───────────────────────────────────────────────────────────────────
  { word: "ANANAS",        hint: "Fruct tropical cu coroană",                       level: 1 },
  { word: "PEPENE",        hint: "Fruct mare, verde pe dinafară, roșu pe dinăuntru",level: 1 },
  { word: "MANGO",         hint: "Fruct tropical galben-portocaliu",                level: 1 },
  { word: "KIWI",          hint: "Fruct mic, brun, verde pe dinăuntru",             level: 1 },
  { word: "CIREȘE",        hint: "Fruct mic, roșu, cu codița lungă",                level: 1 },
  { word: "ZMEURĂ",        hint: "Fruct mic, roșu, crește în pădure",               level: 1 },
  { word: "AVOCADO",       hint: "Fruct verde, cremos, folosit în salate",          level: 2 },
  { word: "GRAPEFRUIT",    hint: "Citric mare, ușor amărui",                        level: 2 },
  { word: "PAPAYA",        hint: "Fruct tropical portocaliu",                       level: 2 },
  { word: "SMOCHINE",      hint: "Fruct dulce, mov, cu semințe mici",               level: 2 },

  // ── Profesii ─────────────────────────────────────────────────────────────────
  { word: "BIOLOG",        hint: "Studiază viața și organismele vii",               level: 1 },
  { word: "GEOGRAF",       hint: "Studiază Pământul și regiunile sale",             level: 1 },
  { word: "FARMACIST",     hint: "Prepară și eliberează medicamente",               level: 1 },
  { word: "ARHITECT",      hint: "Proiectează clădiri",                             level: 2 },
  { word: "CHIRURG",       hint: "Medic care operează",                             level: 2 },
  { word: "STOMATOLOG",    hint: "Medic pentru dinți",                              level: 2 },
  { word: "INFORMATICIAN", hint: "Lucrează cu calculatoare și software",            level: 2 },
  { word: "ECONOMIST",     hint: "Studiază economia și finanțele",                  level: 2 },
  { word: "PSIHOLOG",      hint: "Studiază comportamentul uman",                    level: 2 },
  { word: "ASTROFIZICIAN", hint: "Studiază stelele și universul",                   level: 2 },

  // ── Sport ────────────────────────────────────────────────────────────────────
  { word: "FOTBAL",        hint: "Sport cu 11 jucători și o minge rotundă",         level: 1 },
  { word: "BASCHET",       hint: "Sport cu coș și minge portocalie",                level: 1 },
  { word: "VOLEI",         hint: "Sport cu fileu și minge albă",                    level: 1 },
  { word: "TENIS",         hint: "Sport cu rachetă și minge galbenă",               level: 1 },
  { word: "ÎNOT",          hint: "Sport practicat în apă",                          level: 1 },
  { word: "CICLISM",       hint: "Sport cu bicicleta",                              level: 1 },
  { word: "GIMNASTICĂ",    hint: "Sport cu tumbe și exerciții la sol",              level: 2 },
  { word: "SCRIMĂ",        hint: "Sport cu spada",                                  level: 2 },
  { word: "CAIAC",         hint: "Sport nautic cu pagaie",                          level: 2 },
  { word: "TRIATLON",      hint: "Combinație de înot, ciclism și alergare",         level: 2 },

  // ── Țări ─────────────────────────────────────────────────────────────────────
  { word: "JAPONIA",       hint: "Țara Soarelui Răsare",                            level: 1 },
  { word: "CANADA",        hint: "A doua cea mai mare țară din lume",               level: 1 },
  { word: "NORVEGIA",      hint: "Țara fiordurilor",                                level: 1 },
  { word: "EGIPT",         hint: "Țara piramidelor",                                level: 1 },
  { word: "KENYA",         hint: "Țară africană, patria atletismului",              level: 1 },
  { word: "ISLANDA",       hint: "Insulă cu gheizere și aurore boreale",            level: 1 },
  { word: "BRAZILIA",      hint: "Cea mai mare țară din America de Sud",            level: 2 },
  { word: "AUSTRALIA",     hint: "Continent și țară în același timp",               level: 2 },
  { word: "ARGENTINA",     hint: "Patria tangoului",                                level: 2 },
  { word: "CAMBODGIA",     hint: "Țară din Asia cu templul Angkor Wat",             level: 2 },

  // ── Muzică ───────────────────────────────────────────────────────────────────
  { word: "CHITARĂ",       hint: "Instrument cu coarde ciupite",                    level: 1 },
  { word: "VIOARĂ",        hint: "Instrument cu coarde și arcuș",                   level: 1 },
  { word: "TOBE",          hint: "Instrumente de percuție",                         level: 1 },
  { word: "PIAN",          hint: "Instrument cu clape albe și negre",               level: 1 },
  { word: "HARPĂ",         hint: "Instrument cu coarde verticale",                  level: 1 },
  { word: "CLARINET",      hint: "Instrument de suflat din lemn",                   level: 2 },
  { word: "TROMPETĂ",      hint: "Instrument de suflat din alamă",                  level: 2 },
  { word: "SAXOFON",       hint: "Instrument de jazz inventat de Adolphe Sax",      level: 2 },
  { word: "ACORDEON",      hint: "Instrument cu burduf și clape",                   level: 2 },
  { word: "MANDOLINĂ",     hint: "Instrument cu coarde, asemănător chitarei",       level: 2 },

  // ── Natură ───────────────────────────────────────────────────────────────────
  { word: "VULCAN",        hint: "Munte care erupe lavă",                           level: 1 },
  { word: "CASCADĂ",       hint: "Apă care cade de la înălțime",                    level: 1 },
  { word: "DEȘERT",        hint: "Ținut arid, cu mult nisip",                       level: 1 },
  { word: "SAVANA",        hint: "Câmpie tropicală cu iarbă înaltă",                level: 1 },
  { word: "TORNADĂ",       hint: "Vortex de vânt extrem de puternic",               level: 1 },
  { word: "TSUNAMI",       hint: "Val uriaș cauzat de cutremur submarin",           level: 1 },
  { word: "GHETAR",        hint: "Masă uriașă de gheață în mișcare",                level: 2 },
  { word: "TAIGA",         hint: "Pădure boreală de conifere",                      level: 2 },
  { word: "MLAȘTINĂ",      hint: "Teren umed, mlăștinos",                           level: 2 },
  { word: "RECIF",         hint: "Construcție subacvatică de corali",               level: 2 },

  // ── Mâncare ──────────────────────────────────────────────────────────────────
  { word: "SARMALE",       hint: "Mâncare tradițională românească în foi de varză", level: 1 },
  { word: "MĂMĂLIGĂ",      hint: "Preparat din făină de porumb",                    level: 1 },
  { word: "COZONAC",       hint: "Cozonac dulce de Crăciun",                        level: 1 },
  { word: "PIZZA",         hint: "Preparat italian cu blat și toppinguri",          level: 1 },
  { word: "SUSHI",         hint: "Preparat japonez cu orez și pește",               level: 1 },
  { word: "MUSACA",        hint: "Preparat cu carne tocată și cartofi",             level: 2 },
  { word: "CROISSANT",     hint: "Patiserie franțuzească în formă de semilună",     level: 2 },
  { word: "LASAGNE",       hint: "Preparat italian cu foi de paste și carne",       level: 2 },
  { word: "PAELLA",        hint: "Preparat spaniol cu orez și fructe de mare",      level: 2 },
  { word: "GULAȘ",         hint: "Tocăniță ungurească cu carne și boia",            level: 2 },

  // ── Tehnologie ───────────────────────────────────────────────────────────────
  { word: "ROBOT",         hint: "Mașinărie programată să îndeplinească sarcini",   level: 1 },
  { word: "ECRAN",         hint: "Suprafață pe care se afișează imagini",           level: 1 },
  { word: "BATERIE",       hint: "Sursă de energie electrică portabilă",            level: 1 },
  { word: "SATELIT",       hint: "Obiect care orbitează în jurul Pământului",       level: 1 },
  { word: "TELESCOP",      hint: "Instrument pentru observarea cerului",            level: 2 },
  { word: "MICROSCOP",     hint: "Instrument pentru obiecte foarte mici",           level: 2 },
  { word: "CALCULATOR",    hint: "Dispozitiv electronic de calcul",                 level: 2 },
  { word: "IMPRIMANTĂ",    hint: "Dispozitiv care tipărește documente",             level: 2 },
  { word: "PROCESOR",      hint: "Creierul calculatorului",                         level: 2 },
  { word: "BLUETOOTH",     hint: "Tehnologie wireless de transfer de date",         level: 2 },

  // ── Artă ─────────────────────────────────────────────────────────────────────
  { word: "MOZAIC",        hint: "Artă cu bucăți mici de sticlă sau piatră",        level: 1 },
  { word: "PORTRET",       hint: "Imagine care înfățișează o persoană",             level: 1 },
  { word: "PEISAJ",        hint: "Pictură care reprezintă natura",                  level: 1 },
  { word: "ORIGAMI",       hint: "Arta japoneză a plierii hârtiei",                 level: 1 },
  { word: "PASTEL",        hint: "Creion colorat moale folosit în desen",           level: 1 },
  { word: "ACUARELĂ",      hint: "Tehnică de pictură cu vopsele diluate în apă",    level: 2 },
  { word: "SCULPTURĂ",     hint: "Operă de artă tridimensională",                   level: 2 },
  { word: "CARICATURĂ",    hint: "Desen comic cu trăsături exagerate",              level: 2 },
  { word: "GRAFICĂ",       hint: "Artă vizuală creată pe calculator",               level: 2 },
  { word: "CALOGRAFIE",    hint: "Arta scrierii frumoase",                          level: 2 },

  // ── Mitologie ────────────────────────────────────────────────────────────────
  { word: "DRAGON",        hint: "Creatură mitică care suflă foc",                  level: 1 },
  { word: "UNICORN",       hint: "Cal magic cu corn pe frunte",                     level: 1 },
  { word: "PHOENIX",       hint: "Pasăre mitică care renaște din cenușă",           level: 1 },
  { word: "VRĂJITOR",      hint: "Personaj magic din povești",                      level: 1 },
  { word: "ZÂNA",          hint: "Ființă magică feminină din basme",                level: 1 },
  { word: "BALAUR",        hint: "Dragon din basmele românești",                    level: 1 },
  { word: "MINOTAUR",      hint: "Creatură jumătate om, jumătate taur din mitologia greacă", level: 2 },
  { word: "CENTAUR",       hint: "Creatură jumătate om, jumătate cal",              level: 2 },
  { word: "SIRENA",        hint: "Creatură mitică ce atrage marinarii",             level: 2 },
  { word: "MERMAID",       hint: "Femeie-pește din legende",                        level: 2 },

  // ── Diverse ──────────────────────────────────────────────────────────────────
  { word: "MUZEU",         hint: "Loc unde sunt expuse obiecte de artă sau istorice",level: 1 },
  { word: "STADION",       hint: "Arenă sportivă mare",                             level: 1 },
  { word: "FARMACIE",      hint: "Loc unde se cumpără medicamente",                 level: 1 },
  { word: "ORIZONT",       hint: "Linia unde cerul întâlnește pământul",            level: 1 },
  { word: "CURCUBEU",      hint: "Arc colorat pe cer după ploaie",                  level: 1 },
  { word: "BIBLIOTECĂ",    hint: "Loc unde găsești cărți de împrumutat",            level: 2 },
  { word: "LABORATOR",     hint: "Loc unde se fac experimente",                     level: 2 },
  { word: "PLANETARIU",    hint: "Loc unde se proiectează cerul înstelat",          level: 2 },
  { word: "ACVARIU",       hint: "Loc unde trăiesc pești în bazine de sticlă",      level: 2 },
  { word: "AMBASADĂ",      hint: "Reprezentanță diplomatică a unei țări",           level: 2 },
];

// ── Antonime (Nivel 2 — tabel) ───────────────────────────────────────────────
const ANTONYMS = [
  { clue: "MARE",     answer: "MIC" },
  { clue: "BUN",      answer: "RĂU" },
  { clue: "ALB",      answer: "NEGRU" },
  { clue: "CALD",     answer: "RECE" },
  { clue: "ZI",       answer: "NOAPTE" },
  { clue: "SUS",      answer: "JOS" },
  { clue: "NOU",      answer: "VECHI" },
  { clue: "RAPID",    answer: "LENT" },
  { clue: "GREU",     answer: "UȘOR" },
  { clue: "FERICIT",  answer: "TRIST" },
  { clue: "DESCHIS",  answer: "ÎNCHIS" },
  { clue: "FRUMOS",   answer: "URÂT" },
  { clue: "PUTERNIC", answer: "SLAB" },
  { clue: "LUNG",     answer: "SCURT" },
  { clue: "BOGAT",    answer: "SĂRAC" },
  { clue: "CURAJOS",  answer: "FRICOS" },
  { clue: "ÎNAINTE",  answer: "ÎNAPOI" },
  { clue: "LARG",     answer: "ÎNGUST" },
  { clue: "IUBIRE",   answer: "URĂ" },
  { clue: "DULCE",    answer: "AMAR" },
  { clue: "ÎNALT",    answer: "SCUND" },
  { clue: "PLIN",     answer: "GOL" },
  { clue: "VIU",      answer: "MORT" },
  { clue: "ADEVĂRAT", answer: "FALS" },
];
